# Generated by Django 6.0.2 on 2026-03-07 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_agent', '0001_initial'),
        ('customers', '0005_rentalrequest_checkout_car_condition_and_more'),
        ('users', '0010_agency_account_status_agency_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(choices=[('speeding_violation', 'Speeding Violation'), ('traffic_light_violation', 'Traffic Light Violation'), ('parking_violation', 'Parking Violation'), ('ztl_violation', 'ZTL Violation'), ('toll_violation', 'Toll Violation'), ('vehicle_damage', 'Vehicle Damage'), ('other', 'Other')], default='other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('fine_document', models.FileField(blank=True, null=True, upload_to='fines_documents/')),
                ('additional_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fines', to='users.agencyagent')),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='customers.rentalrequest')),
            ],
        ),
    ]
