# Generated by Django 6.0.2 on 2026-03-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_agent', '0002_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
