# Generated by Django 6.0.2 on 2026-03-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_agent', '0003_fine_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='customer_invoices/'),
        ),
    ]
