# Generated by Django 6.0.2 on 2026-03-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agency_alter_user_role_agencyadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyagent',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='agencyagent',
            name='agent_id',
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='users.agency'),
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='agent_photos/'),
        ),
    ]
