# Generated by Django 6.0.2 on 2026-03-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_agencyagent_agency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='license_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
