# Generated by Django 6.0.2 on 2026-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_license_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agency_agent', 'Agency Agent'), ('agency_admin', 'Agency Admin'), ('super_admin', 'Super Admin')], max_length=20),
        ),
    ]
