# Generated by Django 6.0.2 on 2026-03-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_agencyadmin_is_active_agencyagent_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyadmin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyadmin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyagent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
