# Generated by Django 6.0.2 on 2026-03-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agencyadmin_created_at_agencyadmin_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vip_status',
            field=models.BooleanField(default=False),
        ),
    ]
