# Generated by Django 6.0.2 on 2026-03-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Customer profile picture', null=True, upload_to='customer_photos/'),
        ),
    ]
