# Generated by Django 6.0.2 on 2026-03-06 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='account_status',
            field=models.CharField(default='Active', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='account_type',
            field=models.CharField(default='Agency', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='agency',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='api_status',
            field=models.CharField(default='Connected', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='booking_alerts',
            field=models.BooleanField(default=False, help_text='Alerts for new bookings'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive general email notifications'),
        ),
        migrations.AddField(
            model_name='agency',
            name='last_sync',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='late_return_alerts',
            field=models.BooleanField(default=True, help_text='Alerts for late vehicle returns'),
        ),
        migrations.AddField(
            model_name='agency',
            name='maintenance_alerts',
            field=models.BooleanField(default=True, help_text='Vehicle maintenance reminders'),
        ),
        migrations.AddField(
            model_name='agency',
            name='member_since',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='payment_notifications',
            field=models.BooleanField(default=True, help_text='Notifications for payments received'),
        ),
        migrations.AddField(
            model_name='agency',
            name='permission_level',
            field=models.CharField(default='Agency Admin', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='agency',
            name='pricing_base_model',
            field=models.CharField(default='Standard', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
