# Generated by Django 6.0.2 on 2026-03-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_agency_account_status_agency_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='license_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_licenses/back/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_licenses/front/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('verified', 'Verified'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
    ]
