# Generated by Django 6.0.2 on 2026-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customer_license_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
