# Generated by Django 6.0.2 on 2026-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_agency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
