# Generated by Django 6.0.2 on 2026-03-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_agency_suspended_at_agency_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
