# Generated by Django 6.0.2 on 2026-03-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraservice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
