# Generated by Django 6.0.2 on 2026-03-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_admin', '0002_extraservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
