# Generated by Django 6.0.2 on 2026-03-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_admin', '0003_car_license_plate_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
