services:

  web:
    build: .
    command: >
      bash -c "python manage.py migrate --noinput &&
               python manage.py collectstatic --noinput &&
               gunicorn -k uvicorn.workers.UvicornWorker car_rental.asgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static_root
      - media_volume:/app/media

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-car_rental_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your_secure_db_password}
      - POSTGRES_DB=${DB_NAME:-car_rental_db}
#    ports:
#      - "5432:5432"

  redis:
    image: redis:7-alpine
#    ports:
#      - "6379:6379"

  celery:
    build: .
    command: celery -A car_rental worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A car_rental beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
