# Generated by Django 6.0.2 on 2026-03-04 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_vat_tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Default VAT/Tax percentage (%)', max_digits=5)),
                ('default_security_deposit', models.DecimalField(decimal_places=2, default=0.0, help_text='Default security deposit amount ($)', max_digits=10)),
                ('max_discount_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum discount limit percentage (%)', max_digits=5)),
                ('vip_discount_default', models.DecimalField(decimal_places=2, default=0.0, help_text='VIP discount default percentage (%)', max_digits=5)),
                ('late_return_penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Late return penalty per hour ($/hour)', max_digits=10)),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pricing_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Pricing Rule',
                'verbose_name_plural': 'Global Pricing Rules',
            },
        ),
    ]
