# Generated by Django 6.0.2 on 2026-03-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        ('users', '0006_agencyadmin_created_at_agencyadmin_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved – Ready to Pay'), ('processing', 'Processing via Stripe'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='users.agency')),
            ],
            options={
                'verbose_name': 'Agency Monthly Payout',
                'verbose_name_plural': 'Agency Monthly Payouts',
                'ordering': ['-period_year', '-period_month', 'agency__name'],
                'unique_together': {('agency', 'period_year', 'period_month')},
            },
        ),
    ]
