# Generated by Django 6.0.2 on 2026-03-05 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_commissionpayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='RentHub', max_length=255)),
                ('support_email', models.EmailField(default='support@renthub.com', max_length=254)),
                ('support_phone', models.CharField(default='+8801234567890', max_length=20)),
                ('business_address', models.TextField(blank=True)),
                ('platform_logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/')),
                ('enable_cargo_services', models.BooleanField(default=False, help_text='Allow cargo/goods transportation bookings')),
                ('enable_tracking', models.BooleanField(default=False, help_text='Enable real-time shipment tracking')),
                ('default_insurance', models.BooleanField(default=True, help_text='Include cargo insurance by default')),
                ('default_carrier', models.CharField(blank=True, default='FedEx', max_length=100)),
                ('base_shipping_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('charge_per_kg', models.DecimalField(decimal_places=2, default=2.5, max_digits=8)),
                ('express_shipping_rate', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=500.0, max_digits=12)),
                ('max_weight_kg', models.PositiveIntegerField(default=50)),
                ('max_dimensions_cm', models.CharField(default='100x100x100', help_text='L×W×H in cm', max_length=50)),
                ('enable_standard_delivery', models.BooleanField(default=True)),
                ('standard_delivery_days', models.CharField(default='5-7 business days', max_length=50)),
                ('enable_express_delivery', models.BooleanField(default=False)),
                ('express_delivery_days', models.CharField(default='2-3 business days', max_length=50)),
                ('enable_same_day_delivery', models.BooleanField(default=False)),
                ('same_day_delivery_description', models.CharField(default='Within 24 hours', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
