# Generated by Django 6.0.2 on 2026-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='privacy_policy',
            field=models.TextField(default='By signing up, you agree to our Privacy Policy.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='terms_and_conditions',
            field=models.TextField(default='By signing up, you agree to our Terms and Conditions.'),
        ),
    ]
