# Generated by Django 6.0.2 on 2026-03-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_rentalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
