# Generated by Django 6.0.2 on 2026-03-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rentalrequest_rejection_reason'),
        ('users', '0010_agency_account_status_agency_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='billing_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='billing_same_as_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='cargo_sync_status',
            field=models.CharField(blank=True, default='Not Synced', max_length=50),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_car_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_completed', to='users.agencyagent'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_fuel_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkin_starting_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='document_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_documents/back/'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='document_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='document_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_documents/front/'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='document_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='inspection_photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
