# Generated by Django 6.0.2 on 2026-03-07 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rentalrequest_billing_address_and_more'),
        ('users', '0010_agency_account_status_agency_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_car_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_completed', to='users.agencyagent'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_damage_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_damage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_ending_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_extra_charge_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_extra_km_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_fuel_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_fuel_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_invoice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_late_return_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_return_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='checkout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
