name: Django CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        python manage.py test
      env:
        # These secrets are required for the test pass
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        DATABASE_URL: sqlite:///:memory:

  deploy:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /home/${{ secrets.VPS_USER }}/Car-Rental-Management
          cd /home/${{ secrets.VPS_USER }}/Car-Rental-Management

          if [ ! -d ".git" ]; then
            git clone git@github.com:mohammadSelimReza/Car-Rental-Management.git .
          else
            git pull origin main
          fi
          
          # Recreate .env file from GitHub Secret
          echo "${{ secrets.ENV_FILE }}" > .env
          
          docker compose up -d --build
          docker compose exec -T web python manage.py migrate
          docker compose exec -T web python manage.py collectstatic --noinput
